[package]
name = "presenceforge"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.5"
libc = "0.2"
